# Initialize

## Pytorch

In [1]:
# https://github.com/deep-learning-with-pytorch/dlwpt-code
import torch as th
print("Version: {}".format(th.version.__version__))
print("Num GPU: {}".format(th.cuda.device_count()))

if th.cuda.is_available():
  n_gpu = th.cuda.device_count()
  for i in range(n_gpu):
    print("GPU {}: {}".format(i, th.cuda.get_device_name(i)))

Version: 2.1.0+cu121
Num GPU: 1
GPU 0: Tesla T4


In [2]:
a = th.ones(3,3)
b = th.ones(3,3)
a + b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [3]:
a = a.to('cuda')
b = b.to('cuda')
a + b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0')

## Tensorflow

In [4]:
import tensorflow as tf
print("Version: {}".format(tf.__version__))
print("Num GPU: {}".format(tf.config.list_physical_devices('GPU')))


Version: 2.15.0
Num GPU: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [5]:
a = tf.ones(3,3)
b = tf.ones(3,3)
(a + b).numpy()

array([2, 2, 2], dtype=int32)

In [6]:
# by default, Tensorflow tensor will use GPU if there's any
a.device

'/job:localhost/replica:0/task:0/device:GPU:0'

# Working with Tensor

## how to construct

### Pytorch: convert array to tensor

In [21]:
a = [1, 2, 3]
th.tensor(a)

tensor([1, 2, 3])

In [22]:
# tensor only hold numbers
a.append("4")
th.tensor(a)

TypeError: ignored

### Tensorflow: convert array to tensor

In [16]:
a = [1, 2, 3]
tf.convert_to_tensor(a)


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [18]:
# tensor cannot mix data types, but can use str type
a.append("4")
tf.convert_to_tensor(["a"])

<tf.Tensor: shape=(1,), dtype=string, numpy=array([b'a'], dtype=object)>

### Pytorch: use functions for initialize

In [23]:
# TODO: check type of points variable
points = th.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [10]:
# prompt: check type of points tensor variable

points.type()


'torch.FloatTensor'

In [11]:
# ask the tensor about its shape
points.shape

torch.Size([6])

In [12]:
points = th.ones(3, 3)
points.shape

torch.Size([3, 3])

### Tensorflow: use functions for initialize

In [25]:
# In TensorFlow, you cannot directly assign values to individual elements of a tensor after its creation because tensors are immutable.
# If you need a mutable tensor (i.e., a tensor whose values can be changed after creation), you can use tf.Variable.
points = tf.Variable(tf.zeros(6, dtype=tf.float32))
points.assign([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

<tf.Variable 'Variable:0' shape=(6,) dtype=float32, numpy=array([4., 1., 5., 3., 2., 1.], dtype=float32)>

In [27]:
# check type of points tensor variable
points.dtype


tf.float32

In [28]:
# ask the tensor about its shape
points.shape

TensorShape([6])

In [31]:
# The tf.ones function should be provided a tuple as an argument to specify the shape of the tensor.
points = tf.ones((3, 3))
points.shape

TensorShape([3, 3])

## Pytorch: how to access

In [13]:
points = th.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

### using two indices

In [15]:
points[0]

tensor([4., 1.])

In [14]:
points[0, 1]

tensor(1.)

In [16]:
some_list = list(range(6))
some_list = th.tensor(some_list)
some_list

tensor([0, 1, 2, 3, 4, 5])

In [17]:

# all elements in the list
print(some_list[:])


# from element 1 inclusive to element 4 exclusive
print(some_list[1:4])


# from element 1 inclusive to the end of the list
print(some_list[1:])


# from the start of the list to element 4 exclusive
print(some_list[:4])


# from the start of the list to one before the last element
print(some_list[:-1])


# from element 1 inclusive to element 4 exclusive in steps of 2
print(some_list[1:4:2])

tensor([0, 1, 2, 3, 4, 5])
tensor([1, 2, 3])
tensor([1, 2, 3, 4, 5])
tensor([0, 1, 2, 3])
tensor([0, 1, 2, 3, 4])
tensor([1, 3])


In [18]:
# All rows after first, implicitly all columns
print(points[1:])


# All rows after first, all columns
print(points[1:, :])


# All rows after first, first column
print(points[1:, 0])


# Add dimension of size one, just like unsqueeze
print(points[None])

tensor([[5., 3.],
        [2., 1.]])
tensor([[5., 3.],
        [2., 1.]])
tensor([5., 2.])
tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])


In [19]:
# unsqueze first dimension
points[None].shape

torch.Size([1, 3, 2])

## Tensorflow: how to access

In [32]:
points = tf.convert_to_tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[4., 1.],
       [5., 3.],
       [2., 1.]], dtype=float32)>

### using two indices

In [33]:
points[0]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4., 1.], dtype=float32)>

In [34]:
points[0, 1]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [35]:
some_list = list(range(6))
some_list = tf.convert_to_tensor(some_list)
some_list

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5], dtype=int32)>

In [36]:

# all elements in the list
print(some_list[:])


# from element 1 inclusive to element 4 exclusive
print(some_list[1:4])


# from element 1 inclusive to the end of the list
print(some_list[1:])


# from the start of the list to element 4 exclusive
print(some_list[:4])


# from the start of the list to one before the last element
print(some_list[:-1])


# from element 1 inclusive to element 4 exclusive in steps of 2
print(some_list[1:4:2])

tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([1 3], shape=(2,), dtype=int32)


In [37]:
# All rows after first, implicitly all columns
print(points[1:])


# All rows after first, all columns
print(points[1:, :])


# All rows after first, first column
print(points[1:, 0])


# Add dimension of size one, just like unsqueeze
print(points[None])

tf.Tensor(
[[5. 3.]
 [2. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[5. 3.]
 [2. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor([5. 2.], shape=(2,), dtype=float32)
tf.Tensor(
[[[4. 1.]
  [5. 3.]
  [2. 1.]]], shape=(1, 3, 2), dtype=float32)


In [38]:
# unsqueze first dimension
points[None].shape

TensorShape([1, 3, 2])

## tensor types

Here’s a list of the possible values for the `dtype` argument:
- **torch.float32 or torch.float**: 32-bit floating point (default)
- torch.float64 or torch.double: 64-bit, double precision floating point (will not buy us improvements in the accuracy of a model and will require more memory and computing time)
- torch.float16 or torch.half: 16-bit, half precision floating point (switch to half-precision to decrease the footprint of a neural network model if needed, with minor impact on accuracy)
- torch.int8: signed 8-bit integers
- torch.uint8: unsigned 8-bit integers
- torch.int16 or torch.short: signed 16-bit integers
- torch.int32 or torch.int: signed 32-bit integers
- **torch.int64 or torch.long**: signed 64-bit integers (Tensors can be used as indexes in other tensors)
- torch.bool: boolean

### Pytorch: explicit type

In [20]:
double_points = th.ones(10, 2, dtype=th.double)
double_points.type()


'torch.DoubleTensor'

In [21]:
short_points = th.tensor([[1, 2], [3, 4]], dtype=th.short)
short_points.type()

'torch.ShortTensor'

### casting by creation function

In [ ]:
# cast the output of a tensor creation function to the right type using the corresponding casting method
double_points = th.zeros(10, 2).double()
short_points = th.ones(10, 2).short()

In [ ]:
# Under the hood, to checks and performs the conversion if needed
double_points = th.zeros(10, 2).to(th.double)
short_points = th.ones(10, 2).to(dtype=th.short)

In [ ]:
# inputs are converted to the larger type automatically
points_64 = th.rand(5, dtype=th.double)
points_short = points_64.to(th.short)
points_64 * points_short # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

### Tensorflow: explicit type

In [39]:
double_points = tf.ones((10, 2), dtype=tf.float64)
print(double_points.dtype)

<dtype: 'float64'>


In [40]:
short_points = tf.constant([[1, 2], [3, 4]], dtype=tf.int16)
print(short_points.dtype)

<dtype: 'int16'>


### casting by creation function

In [41]:
# cast the output of a tensor creation function to the right type using the corresponding casting method
double_points = tf.zeros((10, 2), dtype=tf.float64)
short_points = tf.ones((10, 2), dtype=tf.int16)

In [42]:
# Create a random tensor with double precision in TensorFlow
points_64 = tf.random.uniform((5,), dtype=tf.float64)

# Cast the tensor to short integer type
points_short = tf.cast(points_64, dtype=tf.int16)

# Perform element-wise multiplication
result = points_64 * tf.cast(points_short, dtype=tf.float64)

# Display the result
print(result.numpy())


[0. 0. 0. 0. 0.]


## tensor API

tensor operations divided into groups:

- *Creation ops* — functions for constructing a tensor, like `ones` and `from_numpy`
- *Indexing, slicing, joining, mutating ops* — functions for changing the shape, stride or content a tensor, like `transpose`
- *Math ops* — functions for manipulating the content of the tensor through computations
    - *Pointwise ops* — functions for obtaining a new tensor by applying a function to each element independently, like `abs` and `cos`
    - *Reduction ops* — functions for computing aggregate values by iterating through tensors, like `mean`, `std` and `norm`
    - *Comparison ops* — functions for evaluating numerical predicates over tensors, like `equal` and `max`
    - *Spectral ops* — functions for transforming in and operating in the frequency domain, like `stft` and `hamming_window`
    - *Other operations* — special functions operating on vectors, like `cross`, or matrices, like `trace`
    - *BLAS and LAPACK operations* — functions following the BLAS (Basic Linear Algebra Subprograms) specification for scalar, vector-vector, matrix-vector and matrix-matrix operations
- *Random sampling* — functions for generating values by drawing randomly from probability distributions, like `randn` and `normal`
- *Serialization* — functions for saving and loading tensors, like `load` and `save`
- *Parallelism* — functions for controlling the number of threads for parallel CPU execution, like set_num_threads

In [ ]:
help(th.transpose)

Help on built-in function transpose:

transpose(...)
    transpose(input, dim0, dim1) -> Tensor
    
    Returns a tensor that is a transposed version of :attr:`input`.
    The given dimensions :attr:`dim0` and :attr:`dim1` are swapped.
    
    The resulting :attr:`out` tensor shares it's underlying storage with the
    :attr:`input` tensor, so changing the content of one would change the content
    of the other.
    
    Args:
        input (Tensor): the input tensor.
        dim0 (int): the first dimension to be transposed
        dim1 (int): the second dimension to be transposed
    
    Example::
    
        >>> x = torch.randn(2, 3)
        >>> x
        tensor([[ 1.0028, -0.9893,  0.5809],
                [-0.1669,  0.7299,  0.4942]])
        >>> torch.transpose(x, 0, 1)
        tensor([[ 1.0028, -0.1669],
                [-0.9893,  0.7299],
                [ 0.5809,  0.4942]])



In [ ]:
a = th.ones(3, 2)
a_t = th.transpose(a, 0, 1)
a_T = a.T
a.shape, a_t.shape, a_T.shape

(torch.Size([3, 2]), torch.Size([2, 3]), torch.Size([2, 3]))

In [ ]:
# channel, width, height
x = th.randn(3, 4, 5)
x

tensor([[[ 0.6129, -1.0861,  0.2060, -0.1801, -0.4003],
         [ 0.9179,  1.0771,  0.3784, -1.1029, -1.2151],
         [-1.1081, -0.6974, -1.6236,  0.2828,  0.1465],
         [-0.2114,  0.7404,  0.3971, -1.4299, -2.7948]],

        [[-1.6315, -0.5044, -1.0696, -0.8673,  0.3604],
         [ 0.5027,  1.1823, -0.3937,  0.2373,  0.8007],
         [-0.1426, -0.4951,  0.3680, -1.0588, -0.5099],
         [ 2.3760,  0.0909, -0.4048,  0.3511, -0.2651]],

        [[-1.2032,  0.1402,  0.0725, -0.1797,  0.4126],
         [ 0.7845, -0.5688,  0.1781,  0.3818,  0.7012],
         [ 0.4385,  1.8912,  0.8337, -0.1282, -0.1837],
         [ 0.6653, -0.6568, -0.2258,  0.1248,  0.5393]]])

In [ ]:
# width, height, channel
x_t = x.transpose(0, 1).transpose(1, 2)
x_t

tensor([[[ 0.6129, -1.6315, -1.2032],
         [-1.0861, -0.5044,  0.1402],
         [ 0.2060, -1.0696,  0.0725],
         [-0.1801, -0.8673, -0.1797],
         [-0.4003,  0.3604,  0.4126]],

        [[ 0.9179,  0.5027,  0.7845],
         [ 1.0771,  1.1823, -0.5688],
         [ 0.3784, -0.3937,  0.1781],
         [-1.1029,  0.2373,  0.3818],
         [-1.2151,  0.8007,  0.7012]],

        [[-1.1081, -0.1426,  0.4385],
         [-0.6974, -0.4951,  1.8912],
         [-1.6236,  0.3680,  0.8337],
         [ 0.2828, -1.0588, -0.1282],
         [ 0.1465, -0.5099, -0.1837]],

        [[-0.2114,  2.3760,  0.6653],
         [ 0.7404,  0.0909, -0.6568],
         [ 0.3971, -0.4048, -0.2258],
         [-1.4299,  0.3511,  0.1248],
         [-2.7948, -0.2651,  0.5393]]])

In [ ]:
x_t.shape

torch.Size([4, 5, 3])

In [ ]:
a.shape

torch.Size([3, 2])

### Tensorflow API

In [43]:
help(tf.transpose)

Help on function transpose_v2 in module tensorflow.python.ops.array_ops:

transpose_v2(a, perm=None, conjugate=False, name='transpose')
    Transposes `a`, where `a` is a Tensor.
    
    Permutes the dimensions according to the value of `perm`.
    
    The returned tensor's dimension `i` will correspond to the input dimension
    `perm[i]`. If `perm` is not given, it is set to (n-1...0), where n is the rank
    of the input tensor. Hence, by default, this operation performs a regular
    matrix transpose on 2-D input Tensors.
    
    If conjugate is `True` and `a.dtype` is either `complex64` or `complex128`
    then the values of `a` are conjugated and transposed.
    
    @compatibility(numpy)
    In `numpy` transposes are memory-efficient constant time operations as they
    simply return a new view of the same data with adjusted `strides`.
    
    TensorFlow does not support strides, so `transpose` returns a new tensor with
    the items permuted.
    @end_compatibility
    
   

In [45]:
# Create a tensor in TensorFlow
a = tf.ones((3, 2))

# Transpose the tensor using tf.transpose
a_t = tf.transpose(a)

# Display shapes
print("Shape of 'a':", a.shape)
print("Shape of 'a_t':", a_t.shape)

Shape of 'a': (3, 2)
Shape of 'a_t': (2, 3)


In [52]:
# channel, width, height
x = tf.random.normal((3, 4, 5))
print(x.numpy())

[[[-0.96740973 -0.21028432  0.57413334  0.04485273 -0.06448968]
  [-0.7820705   1.3168079   0.40004602  0.37896323 -0.7049793 ]
  [-1.1092622  -0.9547596  -0.89671636  0.8454389  -0.4644031 ]
  [-2.2274308  -0.3634513   0.59084433  1.9515187  -1.8662384 ]]

 [[-0.42351848  0.9788369  -0.7704858  -0.98847526 -0.7535862 ]
  [-0.00769763  0.93383026  0.67689365  2.3638947   0.9465776 ]
  [ 0.09959887  0.84971935  0.41143066 -0.6721825  -0.39503816]
  [ 0.4435776   0.4284796  -1.5060557   1.6148745   0.7134626 ]]

 [[-1.704947    0.12709238  0.05682719  0.00394407 -0.26646376]
  [ 1.860848    1.4126606   0.09281349 -0.77239484  1.1841223 ]
  [ 0.5577139  -0.54320246  0.6822827   0.14335786 -0.13572979]
  [-0.39030734  0.9610356  -0.49045894 -0.14189696  2.6830993 ]]]


In [53]:
# width, height, channel
x_t = tf.transpose(x, perm=[1, 0, 2])
x_t = tf.transpose(x_t, perm=[1, 0, 2])
x_t

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[-0.96740973, -0.21028432,  0.57413334,  0.04485273,
         -0.06448968],
        [-0.7820705 ,  1.3168079 ,  0.40004602,  0.37896323,
         -0.7049793 ],
        [-1.1092622 , -0.9547596 , -0.89671636,  0.8454389 ,
         -0.4644031 ],
        [-2.2274308 , -0.3634513 ,  0.59084433,  1.9515187 ,
         -1.8662384 ]],

       [[-0.42351848,  0.9788369 , -0.7704858 , -0.98847526,
         -0.7535862 ],
        [-0.00769763,  0.93383026,  0.67689365,  2.3638947 ,
          0.9465776 ],
        [ 0.09959887,  0.84971935,  0.41143066, -0.6721825 ,
         -0.39503816],
        [ 0.4435776 ,  0.4284796 , -1.5060557 ,  1.6148745 ,
          0.7134626 ]],

       [[-1.704947  ,  0.12709238,  0.05682719,  0.00394407,
         -0.26646376],
        [ 1.860848  ,  1.4126606 ,  0.09281349, -0.77239484,
          1.1841223 ],
        [ 0.5577139 , -0.54320246,  0.6822827 ,  0.14335786,
         -0.13572979],
        [-0.39030734,

In [54]:
x_t.shape

TensorShape([3, 4, 5])

## Storage

Storage is a one-dimensional array of numerical data, i.e. a contiguous block of memory containing numbers of a given type

Even though the tensor reports itself as having 3 rows and 2 columns, the storage under the hood is a contiguous array of size 6. In this sense, the tensor just knows how to translate a pair of indices into a location in the storage.

In [ ]:
points = th.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [ ]:
# changing the value of a storage leads to changing the content of its referring tensor
points_storage = points.storage()
points_storage[0] = 2.0
points


tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

Methods of the tensor object are recognizable from a trailing underscore in their name, like zero_, which indicates that the method operates in-place, by modifying the input instead of creating a new output tensor and returning it.

Any method without the trailing underscore leaves the source tensor unchanged, and instead returns a new tensor.

In [ ]:
a = th.ones(3, 2)
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## tensor metadata: size, offset, stride

- Storage offset is the index in the storage corresponding to the first element in the tensor
- Stride is the number of elements in the storage that need to be skipped over to obtain the next element along each dimension

In [ ]:
points = th.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
second_point = points[1]
second_point.storage_offset()

2

In [ ]:
help(second_point.storage_offset)

Help on built-in function storage_offset:

storage_offset(...) method of torch.Tensor instance
    storage_offset() -> int
    
    Returns :attr:`self` tensor's offset in the underlying storage in terms of
    number of storage elements (not bytes).
    
    Example::
    
        >>> x = torch.tensor([1, 2, 3, 4, 5])
        >>> x.storage_offset()
        0
        >>> x[3:].storage_offset()
        3



In [ ]:
# stride = 2 for next element
second_point.size()

torch.Size([2])

In [ ]:
x = th.tensor([1, 2, 3, 4, 5])
print("Offset: {}".format(x.storage_offset()))
print("Stride: {}".format(x.size()))

print("Offset: {}".format(x[3:].storage_offset()))
print("Stride: {}".format(x[3:].size()))

Offset: 0
Stride: torch.Size([5])
Offset: 3
Stride: torch.Size([2])


### another example: offset, stride, contigous

In [ ]:
X = th.tensor([[1., 2.], [3., 4.], [5., 6.]])
X.storage()

 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
[torch.FloatStorage of size 6]

In [ ]:
X_chunk = X[2]
X_chunk, X_chunk.storage_offset()

(tensor([5., 6.]), 4)

In [ ]:
X_t = X.transpose(0,1)
X_t.storage(), X_t.shape

( 1.0
  2.0
  3.0
  4.0
  5.0
  6.0
 [torch.FloatStorage of size 6], torch.Size([2, 3]))

In [ ]:
id(X_t.storage())==id(X.storage())

True

In [ ]:
X.stride()

(2, 1)

In [ ]:
X_t.stride()

(1, 2)

In [ ]:
X_prime = th.tensor([[1., 3., 5.],
                        [2., 4., 6.]])
X_prime.stride(), X_prime.storage()

((3, 1),  1.0
  3.0
  5.0
  2.0
  4.0
  6.0
 [torch.FloatStorage of size 6])

In [ ]:
X_prime.is_contiguous(), X_t.is_contiguous()

(True, False)

In [ ]:
X_t = X_t.contiguous()
X_t.is_contiguous()

True

In [ ]:
X_t.storage()

 1.0
 3.0
 5.0
 2.0
 4.0
 6.0
[torch.FloatStorage of size 6]